### ISSUE TITLE
Easy/built-in way (through the ZAP-exposed API status?) to know when ZAP is ready for its 1st (e.g. open-url, etc.) command

### ISSUE THREAD

**Issue by stephendonner** [Grunny/zap-cli#14]
First and foremost - thanks for this simply elegant and flexible tool, @Grunny!  I'm only now really starting to dig in, with (hopefully) most of my systems and infra work out of the way...

https://blog.mozilla.org/webqa/2016/06/28/dockerized-owasp-zap-security-scanning-in-jenkins-part-two/
https://blog.mozilla.org/webqa/2016/07/07/tough-lessons-learned-from-integrating-docker-zap-cli-and-jenkins/

It'd be really great if there were an easy/easier way to ensure that the ZAP client -- through its API -- were ready to begin other commands; such as at least the 1st, "open-url".  

https://github.com/stephendonner/docker-zap/issues/1 mentions a script workaround, but also points to a commit on May 9th in the "develop" branch - perhaps that can be incorporated?

https://github.com/zaproxy/zaproxy/commit/1049e1dadcc8f278714b08d0c320a9c2d33eefa8

**Comment by Grunny** [comment]
Hi, @stephendonner! Glad you found it useful. :)

Yep, zap-cli already does a check similar to the example Simon gave when running the start command to start the zap daemon:
* https://github.com/Grunny/zap-cli/blob/f19035cc5b1/zapcli/zap_helper.py#L86-L90
* https://github.com/Grunny/zap-cli/blob/f19035cc5b1/zapcli/zap_helper.py#L111-L121

And we can certainly make use of newer functionalities in the API to make that cleaner. :) I imagine the `zap-cli start` command wouldn't work for the needs of the Docker daemon since the command finishes when the daemon is running so it might shut down the instance?

As for running that check to wait for ZAP with other commands such as open URL. We can definitely do that, though I'm thinking about the best approach.  We could check `is_running` on each command, or make an optional wait parameter for all commands so it only waits if you intend it to, rather than failing fast by default if ZAP isn't running because you haven't started it. Or we could just add a command that checks if ZAP is running and does the wait for configurable amount of time (i.e. something like `zap-cli check-zap --timeout 60` (will think of an appropriate command name)). What do you think? :)

**Comment by Grunny** [comment]
@stephendonner Let me know what you think of this as a quick solution: https://github.com/Grunny/zap-cli/pull/16 

The commit to the develop branch looks like it's just for the Java ClientAPI and it's not available in the Python API client right now.

**Comment by Grunny** [comment]
@stephendonner A new version of zap-cli has been published to [PyPI](https://pypi.python.org/pypi/zapcli) so it should be available in the Docker images the next time they're rebuilt and published. :)

**Comment by stephendonner** [comment]
Sorry as always for the slow response, @Grunny :-(

I'm using this to great avail in https://github.com/stephendonner/docker-zap/commit/9e836057a8fd8604584d9df16662dece2a3338f4

https://pastebin.mozilla.org/8906539

Thanks again for the work on this + other Issues!

**Comment by Grunny** [comment]
Glad to hear! Let me know if you run into any other issues or have any suggestions. :)
