### ISSUE TITLE
Is there an attack option?

### ISSUE THREAD

**Issue by McMatty** [Grunny/zap-cli#15]
First thanks for this code - makes everything far simpler.

Having two issues however:

1. -sc is hitting a timeout error waiting for the daemon to launch, this could just be a limitation of the under powered machine its running on

2. I am unable to have a full attack run. Is this a limitation of Zap-Cli or the API?
The active-scan just seems to run the zaproxy quick start scan, but not the full attack scan which is where I would find most High risk issues.

Am I missing something here?

Again awesome piece of work here.

**Comment by Grunny** [comment]
Hi @McMatty! I'm glad you've found the tool useful! :)

> -sc is hitting a timeout error waiting for the daemon to launch, this could just be a limitation of the under powered machine its running on

The `zap-cli start` command and the `-sc` option with `quick-scan` both wait 60 seconds for ZAP to start right now and otherwise raise a timeout error. We can increase this timeout time to something longer or make it configurable. Do you have an idea of roughly how long ZAP takes to fully start up on your machine?

> I am unable to have a full attack run. Is this a limitation of Zap-Cli or the API?
> The active-scan just seems to run the zaproxy quick start scan, but not the full attack scan which is where I would find most High risk issues.

The `active-scan` command should be the same as using "Attack" -> "Active Scan" via the GUI. Can you give examples of what parts of a full attack are not currently happening when running the active-scan command so I can look into what might be missing/broken? And are you using the recursive option (`-r`) with it (i.e. `zap-cli active-scan -r http://127.0.0.1/` with any other options as needed)?

**Comment by McMatty** [comment]
Just following this up.
Issue 2 was the result of the way I built the command up, I hadn't copied pasted the supplied example and as such the full attack was not running correctly.
