### ISSUE TITLE
Move alert processing feature from baseline scan to cli?

### ISSUE THREAD

**Issue by omerlh** [Grunny/zap-cli#19]
Hey
The zap [baseline scan](https://github.com/zaproxy/zaproxy/wiki/ZAP-Baseline-Scan) has the ability to process zap alerts, and return status code based on the alert. This could be useful when using zap as part of CI flow, so you can configure the alert that important to you and then fail the build if they found. I think it might be nice to add it as a command to the CLI, so I can use it also in another flow that are not baseline quick scan, for example, after running zap proxy and scan manually.

What do you think?

**Comment by Grunny** [comment]
Hi @omerlh, I think this is a great idea, thanks for the suggestion. Being able to use the same file for both makes a lot of sense.

**Comment by omerlh** [comment]
Great, so I will try to create a PR today/tomorrow and add a new command - testAlert? Sound good?

**Comment by Grunny** [comment]
Sure, I think you can modify the existing `alerts` command to take the config file as input and do the filtering based on that. It currently has an alert level option that lets you say you only want to output alerts of a given level (i.e. High, Informational, etc.) and an `--exit-code` option that outputs an exit code with the number of alerts of the given level so you could fail the build. So, adding an additional config file option that can be used as an alternative to the alert level option would be good I think. What do you think? :)

**Comment by omerlh** [comment]
Actually that sound pretty good suggestion. Just to be sure I also [asked](https://groups.google.com/forum/#!topic/zaproxy-develop/Ilaoycklf1c) at the Zap development group to hear other thought as I want finally to reuse the code and not duplicate it. Look like baseline scan is not using the CLI, so it might not be a good idea. On the other hand, after this change, we can use the CLI to do the whole baseline scan - and even add a command for baseline scan as the CLI already has the whole functionality.

**Comment by omerlh** [comment]
Currently, I am thinking of trying a bit different approach. I decided to start with something small - using the existing `alert` command (that you already mentioned) - just to fail the build if alerts found. 

The reason for the change - I think that the alert processing logic should be a bit more complicated that what I already did. For example, the baseline scan added the ability to mark an issue as something you are working on so it will be ignored. Personally, I am thinking about an interactive script that goes over the alerts and let you decide if you want to ignore or snooze them. I hope to do it in the near future - but I am not sure such functionality should be part of the CLI. 

What do you think? Does that make sense?

**Comment by Grunny** [comment]
Hmm, let me check my understanding of what you're after. If we just want to fail the build if alerts of a given level are found, then you can use the available `--exit-code` param on the existing `alerts` command ([which defaults to true](https://github.com/Grunny/zap-cli/blob/master/zapcli/cli.py#L231-L232)) but it only allows failing based on ZAP's existing definition of the level (i.e. the default High for XSS, CSRF, etc.). If you're wanting to ignore a type of alert completely, you can also just disable that scanner ID (which you can do with either the `scanners` command or a param for the `quick-scan` command), which will stop the scan from including tests for that issue (which if you're going to ignore it anyway, can save some time on the scan). I think you're wanting this for passive scanning as well, so we can also easily add a command for turning passive scanners on and off (the `scanners` command only deals with the active scan issues).

What you can't do currently with `zap-cli` is change the alert level for a given issue ID, and you can't ignore an instance of an alert (i.e. you can't mark an issue on a specific URL/param/etc. to be ignored, only the given issue ID for all instances of that issue). So, is ignoring an instance of an issue on a specific URL/param/etc. what you want to do?

What I currently do in the CI infrastructure where I work is store the issues from previous active scans and have them marked as either false positives, or ticket filed/in progress/fixed/etc. so that subsequent scans will only alert on new issues or regressions so we don't get alert fatigue :). Something like that built into `zap-cli` could be useful, but we would need to think how it should work, perhaps being able to mark each issue as to be ignored and save that in a config file that can be used in future scans?

**Comment by omerlh** [comment]
What you are describing sound to me like a perfect solution. Do you have any experience with [snyk](https://snyk.io)? Their CLI allow similar functionality: You can iterate the issues it finds, and either ignore or snooze them. It works pretty similar to what you describe...

I just not sure this functionality should be part of the CLI, as it might be too specific - and not generic ZAP option.

**Comment by Grunny** [comment]
Yep, I've used snyk before, and I have a similar wrapper around nsp for alerting on vulnerable dependencies.

I think it could make sense to add here as it would be useful to a lot of people I imagine, but I wonder if it should be implemented fully in `zap-cli` or if we could just require the installation of the [Alert Filter addon](https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsAlertFiltersAlertFilter), which I think provides this functionality basically (I haven't fully tested it). So, we could add support for that addon's API methods in `zap-cli` and if people want to use them but don't have it installed, we output a warning telling them to install the addon first. Then if we allow iterating through the alerts in `zap-cli` and marking as ignore, it could just call that API endpoint to store them (and we could add exporting and importing filters so you could save and reuse the settings if you start a new session). What do you think?

**Comment by omerlh** [comment]
Actually, that sound like a good start. Although I think it might be simpler to write the parsing logic in JS - as zap cli already capable of exporting the alerts in JSON format.

**Comment by omerlh** [comment]
@Grunny today I discovered OWASP [GLUE](https://github.com/OWASP/glue) project, and I think this is actually this functionality should be. What do you think? It could be easily a filter...

**Comment by fadiguezel** [comment]
@omerlh Any updates on this issue?

**Comment by omerlh** [comment]
Well, actually I've did some work on [Glue](https://github.com/OWASP/glue), and it's working pretty well now. You can see a working example [here](https://github.com/Soluto/tweek/pull/633) - including alert filtering. So I think we can close this issue...
