### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by brianbeaven** [Grunny/zap-cli#62]
Hello,

I am trying to use zap-cli and I am running into this issue upon attempting to start the process. "ZAP was not found in the path "/zap". You can set the path to where ZAP is installed on your system using the --zap-path command line parameter or by default using the ZAP_PATH environment variable." 

I have ZAP_PATH environment variable set to where ZAP proxy is installed in both User and System variables and I'm still getting that error.

**Comment by brianbeaven** [comment]
Ok, now when I try running zap-cli start I get:


?[1m?[36m[INFO]            ?[0mStarting ZAP daemon
Traceback (most recent call last):
  [stack trace]
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\OWASP\\Zed Attack Proxy\\zap.log'

Any help with this?

**Comment by Grunny** [comment]
For that, you just need to make sure you have write permissions to the file `C:\Program Files\OWASP\Zed Attack Proxy\zap.log`, so I'd create that file and make sure the permissions are correct. This is where the output of the ZAP process itself will be saved.

**Comment by g4z** [comment]
hi, on my Ubuntu system, ZAP is installed in `/opt/ZAP` and this folder and all files therein are owned by the root user. 

I (or any other user) can run ZAP UI using the command `/opt/ZAP/zap.sh` and everything works fine. 

zap-cli seems to want permission to write a log into the directory where ZAP is installed. This assumes that the user running zap-cli has r/w access to the ZAP install.

perhaps it would be possible to add a new flag like `--output` to zap-cli so i can tell it where i want the output written, rather than assuming i have write access to the installation location.

**Comment by Grunny** [comment]
Closing as https://github.com/Grunny/zap-cli/pull/64 is merged.
