### ISSUE TITLE
"Operation not allowed for current mode" encountered when attempting to use scan commands

### ISSUE THREAD

**Issue by emiliandl** [Grunny/zap-cli#63]
Hello,

I've encountered the error "Operation not allowed for current mode" when I attempted to spider the url of a localhost application.

I've followed the steps presented in the readme file:
1. pip install --upgrade zapcli
2. zap-cli start
[INFO]            Starting ZAP daemon
3. zap-cli open-url https://local-url-here
[INFO]            Accessing URL https://local-url-here
4. zap-cli spider https://local-url-here
[INFO]            Running spider...
[ERROR]           Error running spider: "Operation not allowed for current mode"

The environment variables have been set for API_KEY, PATH and PORT.
As it can be seen above, while zap can start and open the url as it is recommended in the readme file, when attempting to spider a target(or when using other actions such as active scans) the zap-cli returns the error mentioned above.

Are there any extra steps required before an attempt to spider a given url can be made?

**Comment by Grunny** [comment]
Hi @emiliandl! This error is because you have ZAP set in either "Protected Mode" or "Safe Mode", so it won't spider or attack a URL that isn't explicitly included in a context. You can read about this [here](https://github.com/zaproxy/zap-core-help/wiki/HelpStartConceptsModes). To fix this, you could change the mode to "Standard Mode" which can be done in the ZAP GUI, which would remove this restriction. Or you can create a context, include your site in that context, and use that when scanning. For example, here's first the same error, then the commands that you can use to make a context and run the scan with it successfully:

```
$ zap-cli spider "http://127.0.0.1/"
[INFO]            Running spider...
[ERROR]           Error running spider: "Operation not allowed for current mode"

$ zap-cli context new MyContext
[INFO]            Creating context with name: MyContext
[INFO]            Context "MyContext" created with ID: 2

$ zap-cli context include -n MyContext -p "http://127.0.0.1.*"
[INFO]            Including regex http://127.0.0.1.* in context with name: MyContext

$ zap-cli spider -c MyContext "http://127.0.0.1/"
[INFO]            Running spider...
```

The context name can also be passed to `active-scan`, `quick-scan`, etc. to make use of it when running those scan commands as well. I hope that helps!

**Comment by emiliandl** [comment]
Thank you @Grunny ! That did the trick. The only missing element was the context in my case.
